name: Deploy to Amazon S3

on:
  push:
    branches:
      - main  # Puede ser main o cualquier otra rama desde la que desees desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} #Accey key de IAM
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #Secret key de IAM
        aws-region: 'eu-west-1'  # Reemplaza con la región de tu bucket de S3

    - name: Deploy to S3
      run: aws s3 sync ./ s3://restart-simple-web --delete
